export const RangeSliderModul = [
  {
    id: "pressure",
    min: 100,
    max: 150,
    clName: "rangeSlider",
    text: "optimal range for systolic blood pressure",
  },
  {
    id: "hdl",
    min: 30,
    max: 100,
    clName: "rangeSlider hdl",
    text: "optimal range for HDL",
  },
  {
    id: "trigl",
    min: 50,
    max: 400,
    clName: "rangeSlider trigl",
    text: "optimal range for triglycerides",
  },
  {
    id: "glucose",
    min: 70,
    max: 130,
    clName: "rangeSlider glucose",
    text: "optimal range for fasting glucose",
  },
  {
    id: "weight",
    min: 100,
    max: 300,
    clName: "rangeSlider weight",
    text: "",
  },
  {
    id: "diastolicBP",
    min: 60,
    max: 100,
    clName: "rangeSlider diastolicBP",
    text: "optimal range for diastolic blood pressure",
  },
  {
    id: "waist",
    min: 15,
    max: 60,
    clName: "rangeSlider weight",
    text: "",
  },
];
